import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { Saira } from "next/font/google";

const saira = Saira({ subsets: ["latin"] });

export const metadata = {
  title: "BOBBY SADHWANI | PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
